---
- name: Install vapoursynth
  pacman:
    name: vapoursynth
    state: present

- name: Install mpv
  pacman:
    name: mpv
    state: present

  tags:
    - aur

- name: Push play script
  copy: src=play.sh dest=/usr/local/bin/play mode=0755

- name: Install mpv-mpris
  aur:
    name: mpv-mpris
    user: "{{ user.name }}"

  tags:
    - aur

- name: Install playerctrl
  pacman:
    name: playerctl
    state: present
