---
- name: Install vapoursynth
  pacman:
    name: vapoursynth
    state: present

- name: Install mpv
  aur:
    name: mpv-git
    user: "{{ user.name }}"

  tags:
    - aur
- name: Push play script
  copy: src=play.sh dest=/usr/local/bin/play mode=0755
