---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install xdpyinfo
  pacman: name=xorg-xdpyinfo state=present

- name: Install xev
  pacman: name=xorg-xev state=present

- name: Install xorg-sessreg
  pacman: name=xorg-sessreg state=present

- name: Install video driver(s)
  pacman: name={{ item }} state=present
  with_items: "{{ video_drivers }}"

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes

- name: Install xcompmgr
  pacman:
    name: xcompmgr
    state: present

- name: Install xwallpaper
  pacman: name=xwallpaper state=present

- name: Install xssstate
  pacman: name=xssstate state=present

- name: Install xcape
  pacman: name=xcape state=present

- name: Install xvinfo
  pacman:
    name: xorg-xvinfo
    state: present

- name: Install xscreensaver and extra screensavers
  aur:
    name:
      - xscreensaver-arch-logo
      - xscreensaver-aerial
      - xscreensaver-aerial-videos-1080
    user: "{{ user.name }}"
  tags:
    - aur


- name: Install Gruvbox gtk theme
  aur: name=gtk-theme-arc-gruvbox-git user={{ user.name }}
  tags:
    - aur

- include: sxhkd.yml
- include: unclutter.yml
- include: autorandr.yml
- include: srandrd.yml
- include: arandr.yml
- include: alacritty.yml
- include: autocutsel.yml
