---
- name: Install aspell English dictionary
  pacman: name=aspell-en state=present
  tags:
    - weechat

- name: Install weechat
  pacman: name=weechat state=present
  tags:
    - weechat

- name: Install dunst
  pacman: name=dunst state=present
  tags:
    - weechat
