---
- name: Install python pip
  pacman: name={{ item }} state=present
  with_items:
    - python-pip
    - python2-pip
  tags:
    - python

- name: Install some pip packages
  pip: name={{ item }} state=present
  with_items:
    - jedi
    - flake8
    - importmagic
    - autopep8
  tags:
    - python
