---
- name: Install i3
  pacman:
    name:
      - i3-wm
      - i3blocks
      - i3status
    state: present

- name: Install betterlockscreen
  aur:
    name: betterlockscreen
    user: "{{ user.name }}"

- name: Install polybar
  aur:
    name: polybar-git
    user: "{{ user.name }}"

- name: Install py3status
  pacman: name=py3status state=present

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF

- include: rofi.yml
