---
- name: Install GNOME
  pacman: name={{ item }} state=present
  with_items:
    - gnome
    - gnome-extra
    - gnome-tweaks
    - xorg-server-xwayland

- include: dconf.yml
- include: gtk.yml
- include: gnome_shell.yml
- include: online_accounts.yml
