---
- name: Install w3m
  pacman:
    name: w3m
    state: present

- name: Install Firefox
  pacman:
    name: firefox
    state: present
  tags:
    - firefox

- name: Install Tridactyl
  pacman:
    name: firefox-tridactyl
    state: present
  tags:
    - firefox

- name: Install Tridactyl Native
  aur:
    name: firefox-tridactyl-native
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur
    - firefox

- name: Install Google Chrome Dev version
  aur:
    name: google-chrome-dev
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur
    - google-chrome

- name: Install tor-browser
  pacman:
    name: torbrowser-launcher
    state: present
  tags:
    - tor-browser

- name: Install lynx
  pacman:
    name: lynx
    state: present
  tags:
    - lynx

- name: Install Brave browser
  aur:
    name: brave-bin
    user: "{{ user.name }}"
  tags:
    - brave
    - aur

- name: Install qutebrowser
  pacman:
    name: qutebrowser
    state: present
  tags:
    - qutebrowser

- name: Install pdfjs for qutebrowser
  pacman:
    name: pdfjs
    state: present
  tags:
    - qutebrowser

- name: Push rofi browser chooser
  template:
    src: browser.sh.j2
    dest: /usr/local/bin/browser
    mode: 0755
  tags:
    - rofi
    - chooser

- name: Create local desktop application dir
  file:
    path: /usr/local/share/applications
    state: directory
  tags:
    - rofi
    - chooser

- name: Push rofi browser chooser desktop file
  copy:
    src: browser.desktop
    dest: /usr/local/share/applications/browser.desktop
  tags:
    - rofi
    - chooser

- name: Verify mimeapps.list exists
  file:
    path: /etc/xdg/mimeapps.list
    state: touch
  tags:
    - rofi
    - chooser

- name: Set rofi browser chooser as default application for relevant mimetypes
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^text/html=', line: 'text/html=browser.desktop' }
    - { regexp: '^text/xml=', line: 'text/xml=browser.desktop' }
    - { regexp: '^text/mml=', line: 'text/mml=browser.desktop' }
    - { regexp: '^application/xhtml\+xml=', line: 'application/xhtml+xml=browser.desktop' }
    - { regexp: '^application/xml=', line: 'application/xml=browser.desktop' }
    - { regexp: '^x-scheme-handler/http=', line: 'x-scheme-handler/http=browser.desktop' }
    - { regexp: '^x-scheme-handler/https=', line: 'x-scheme-handler/https=browser.desktop' }
  tags:
    - rofi
    - chooser

- name: Install surfraw
  pacman:
    name: surfraw
    state: present
  tags:
    - surfraw

- name: Configure surfraw browser
  lineinfile:
    dest: /etc/xdg/surfraw/conf
    regexp: '^def   SURFRAW_graphical_browser	'
    line: 'def   SURFRAW_graphical_browser	/usr/local/bin/browser'
  tags:
    - surfraw
    - chooser

- name: Push surfraw-rofi script
  copy:
    src: surfraw-rofi
    dest: /usr/local/bin/surfraw-rofi
    mode: 0755
  tags:
    - surfraw
    - rofi
