---
- name: Install Tor
  pacman:
    name:
      - tor
      - torsocks
    state: present

- name: Set Tor to run as tor
  lineinfile: dest=/etc/tor/torrc
              regexp=^User
              state=present
              line="User tor"

