---
- name: Install mpd
  pacman:
    name: mpd
    state: present

- name: Install mpc
  pacman:
    name: mpc
    state: present

- name: Install ncmpcpp
  pacman:
    name: ncmpcpp
    state: present

- name: Install Cava
  aur:
    name: cava
    user: "{{ user.name }}"
  tags:
    - aur

- name: Push mpd service file
  copy: src=mpd.service dest=/etc/systemd/user/mpd.service
  notify:
    - reload systemd config
