---
- name: Install pipenv
  pacman:
      name: python-pipenv
      state: present

- name: Install pyenv
  pacman:
      name: pyenv
      state: present

- name: Install pyenv-virtualenv
  aur:
    name:
      - pyenv-virtualenv
    user: "{{user.name}}"
  tags:
    - aur

- name: Install documentation
  pacman:
      name:
        - python-docs
        - python2-docs
      state: present
