---
- name: Install teiler dependencies
  pacman: name=copyq state=present
  tags:
    - teiler

- name: Install teiler and dependencies
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - xininfo-git
    - teiler-git
  tags:
    - aur
    - teiler
