---
- name: Install freetype2
  pacman:
    name: freetype2
    state: present

- name: Install cairo
  pacman:
    name: cairo
    state: present

- name: Install fontconfig
  pacman:
    name: fontconfig
    state: present

- name: Push font substitutions
  copy:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Install base fonts
  pacman:
    name: "{{ base_fonts }}"
    state: present

- name: Install AUR fonts
  aur:
    name: "{{ aur_fonts }}"
    user: "{{ user.name }}"
  tags:
    - aur
